<template><div class="page"><h2>添加习题</h2><el-alert title="习题将直接进入所选课程题库，发布作业时可立即使用" type="info" :closable="false"/><el-form ref="formRef" :model="form" :rules="rules" label-width="100px" class="form">
<el-form-item label="任教课程" prop="courseId"><el-select v-model="form.courseId" :loading="courseLoading" :placeholder="courseLoading?'正在加载课程...':'请选择课程'" filterable style="width:100%"><el-option v-for="c in courses" :key="c.courseId" :label="`${c.courseName}（${c.category||'未分类'}）`" :value="c.courseId"/></el-select><div v-if="!courseLoading&&!courses.length" class="empty-tip">暂无任教课程，请先创建课程</div></el-form-item>
<el-form-item label="题目内容" prop="content"><el-input v-model="form.content" type="textarea" :rows="5" maxlength="1000" show-word-limit/></el-form-item>
<el-form-item label="难度" prop="difficulty"><el-radio-group v-model="form.difficulty"><el-radio-button value="easy">简单</el-radio-button><el-radio-button value="medium">中等</el-radio-button><el-radio-button value="hard">困难</el-radio-button></el-radio-group></el-form-item>
<el-form-item label="题型" prop="type"><el-select v-model="form.type"><el-option label="单选题" value="single"/><el-option label="多选题" value="multiple"/><el-option label="判断题" value="judge"/><el-option label="填空题" value="blank"/><el-option label="简答题" value="short"/></el-select></el-form-item>
<el-form-item v-if="['single','multiple'].includes(form.type)" label="选项"><div class="options"><el-input v-for="o in form.options" :key="o.key" v-model="o.content"><template #prepend>{{o.key}}</template></el-input></div></el-form-item>
<el-form-item label="正确答案" prop="answer"><el-input v-model="form.answer" placeholder="选择题填 A/AB；判断题填 true/false；填空题填写标准答案"/></el-form-item>
<el-form-item label="知识点"><el-input v-model="form.knowledge"/></el-form-item><el-form-item label="解析说明" prop="analysis"><el-input v-model="form.analysis" type="textarea" :rows="4"/></el-form-item>
<el-form-item><el-button type="primary" :loading="saving" @click="save">保存习题</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></div></template>
<script setup>
import { onMounted, ref } from 'vue';import { ElMessage } from 'element-plus';import { getTeacherCourses } from '../../api/course.js';import { createExercise } from '../../api/exercise.js'
const courses=ref([]),formRef=ref(),saving=ref(false),courseLoading=ref(false);const initial=()=>({courseId:'',content:'',difficulty:'easy',type:'single',answer:'',analysis:'',knowledge:'',score:4,options:['A','B','C','D'].map(key=>({key,content:''}))});const form=ref(initial());const rules={courseId:[{required:true,message:'请选择课程'}],content:[{required:true,message:'请输入题目'}],answer:[{required:true,message:'请输入正确答案'}],analysis:[{required:true,message:'请输入解析'}]};async function loadCourses(){courseLoading.value=true;try{const data=await getTeacherCourses({page:1,size:100});courses.value=Array.isArray(data)?data:(data?.courses||data?.records||[])}catch(error){courses.value=[];ElMessage.error(error.message||'任教课程加载失败')}finally{courseLoading.value=false}}onMounted(loadCourses);function reset(){const selectedCourse=form.value.courseId;form.value=initial();form.value.courseId=selectedCourse;formRef.value?.clearValidate()}async function save(){await formRef.value.validate();if(['single','multiple'].includes(form.value.type)&&form.value.options.filter(o=>o.content.trim()).length<2){return ElMessage.warning('选择题至少填写两个选项')}saving.value=true;try{await createExercise(form.value);ElMessage.success('习题已加入课程题库');reset()}catch(error){ElMessage.error(error.message||'习题保存失败')}finally{saving.value=false}}
</script><style scoped>.page{background:#fff;padding:28px;border-radius:16px;max-width:900px}.form{margin-top:24px}.options{display:grid;gap:10px;width:100%}.empty-tip{color:var(--gray-500);font-size:13px;margin-top:6px}</style>
