<template><div class="page"><div class="head"><div><h2>直播管理</h2><p>安排直播、进入课堂并管理回放</p></div><el-button type="primary" @click="openCreate">创建直播</el-button></div>
<el-tabs v-model="tab"><el-tab-pane label="直播安排" name="rooms"/>
<el-tab-pane label="回放管理" name="replays"/></el-tabs>
<template v-if="tab==='rooms'">
<el-table :data="rooms" v-loading="loading"><el-table-column prop="title" label="直播主题" min-width="180"/><el-table-column prop="course_name" label="课程"/><el-table-column label="计划时间" min-width="180"><template #default="{row}">{{fmt(row.scheduled_start)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="types[row.status]">{{labels[row.status]}}</el-tag></template></el-table-column><el-table-column label="互动"><template #default="{row}">♥ {{row.like_count}}</template></el-table-column><el-table-column label="操作" min-width="280"><template #default="{row}"><el-button v-if="row.status==='scheduled'" type="danger" size="small" @click="enter(row,true)">开播</el-button><el-button v-if="row.status==='live'" type="primary" size="small" @click="enter(row)">进入</el-button><el-button v-if="row.status==='scheduled'" size="small" @click="edit(row)">编辑</el-button><el-button v-if="row.status==='ended'" size="small" @click="replay(row)">回放</el-button><el-button v-if="row.status!=='live'" type="danger" link @click="remove(row)">删除</el-button></template></el-table-column></el-table>
</template>
<template v-else>
<el-table :data="replays" v-loading="loading"><el-table-column prop="title" label="直播主题" min-width="180"/><el-table-column prop="course_name" label="课程"/><el-table-column label="录制时间" min-width="180"><template #default="{row}">{{fmt(row.record_start_time)}}</template></el-table-column><el-table-column label="时长" width="100"><template #default="{row}">{{fmtDuration(row.replay_duration)}}</template></el-table-column><el-table-column label="操作" width="180"><template #default="{row}"><el-button size="small" type="primary" @click="$router.push('/teacher/live/teaching/'+row.room_id)">查看</el-button><el-button size="small" type="danger" @click="delReplay(row)">删除</el-button></template></el-table-column></el-table>
</template>
<el-dialog v-model="visible" :title="form.roomId?'编辑直播':'创建直播'" width="560"><el-form label-width="90px"><el-form-item label="课程" required><el-select v-model="form.courseId" :disabled="!!form.roomId" style="width:100%"><el-option v-for="c in courses" :key="c.courseId" :label="c.courseName" :value="c.courseId"/></el-select></el-form-item><el-form-item label="主题" required><el-input v-model="form.title" maxlength="120"/></el-form-item><el-form-item label="计划时间" required><el-date-picker v-model="form.scheduledStart" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="结束时间"><el-date-picker v-model="form.scheduledEnd" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="简介"><el-input v-model="form.description" type="textarea" maxlength="1000"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>import{ref,onMounted,watch}from'vue';import{useRouter}from'vue-router';import{ElMessage,ElMessageBox}from'element-plus';import{teacherRooms,createRoom,updateRoom,deleteRoom,setReplay,teacherReplays,deleteReplay}from'../../api/live';import{getTeacherCourses}from'../../api/course';const router=useRouter(),tab=ref('rooms'),rooms=ref([]),replays=ref([]),courses=ref([]),loading=ref(false),visible=ref(false),types={scheduled:'info',live:'danger',ended:'success'},labels={scheduled:'未开始',live:'直播中',ended:'已结束'};const blank=()=>({roomId:'',courseId:'',title:'',description:'',scheduledStart:'',scheduledEnd:''});const form=ref(blank()),fmt=v=>v?new Date(v).toLocaleString():'--';const fmtDuration=s=>{if(!s||s<=0)return'--';const m=Math.floor(s/60),r=s%60;return m>0?`${m}分${r}秒`:`${r}秒`};async function load(){loading.value=true;try{const[r,re]=await Promise.all([teacherRooms(),teacherReplays()]);rooms.value=r;replays.value=re||[]}finally{loading.value=false}}async function loadCourses(){const x=await getTeacherCourses({page:1,size:100});courses.value=x.courses||x.list||x.records||[]}function openCreate(){form.value=blank();visible.value=true}function edit(r){form.value={roomId:r.room_id,courseId:r.course_id,title:r.title,description:r.description||'',scheduledStart:String(r.scheduled_start).replace(' ','T'),scheduledEnd:r.scheduled_end?String(r.scheduled_end).replace(' ','T'):''};visible.value=true}async function save(){if(!form.value.courseId||!form.value.title||!form.value.scheduledStart)return ElMessage.warning('请完整填写必填项');form.value.roomId?await updateRoom(form.value.roomId,form.value):await createRoom(form.value);visible.value=false;ElMessage.success('保存成功');load()}async function enter(r,start){router.push(`/teacher/live/teaching/${r.room_id}?start=${start?1:0}`)}async function remove(r){await ElMessageBox.confirm('确认删除该直播安排？','提示');await deleteRoom(r.room_id);load()}async function replay(r){const{value}=await ElMessageBox.prompt('请输入 HTTPS 或本站 /video/ 回放地址','设置回放',{inputValue:r.replay_url||''});await setReplay(r.room_id,value);load()}async function delReplay(r){await ElMessageBox.confirm('确认删除该回放记录？','提示');await deleteReplay(r.room_id);ElMessage.success('回放已删除');load()}watch(tab,()=>{if(tab.value==='replays')load()});onMounted(()=>{load();loadCourses()})</script>
<style scoped>.page{background:#fff;padding:24px;border-radius:16px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.head p{color:#64748b}</style>