<template><div class="page">
<template v-if="stage==='select'"><h2>习题训练</h2><p class="muted">从已选课程的简单、中等客观题中随机抽取 25 题，每题 4 分。</p><div class="chooser"><el-select v-model="courseId" placeholder="请选择已选课程"><el-option v-for="c in courses" :key="c.courseId" :value="c.courseId" :label="`${c.courseName}（可训练 ${c.availableCount} 题）`" :disabled="c.availableCount<25"/></el-select><el-button type="primary" :disabled="!courseId" :loading="loading" @click="start">一键开始训练</el-button></div></template>
<template v-else-if="stage==='answer'"><div class="top"><h2>训练进行中</h2><span>{{index+1}} / {{questions.length}}</span></div><el-progress :percentage="Math.round(index/questions.length*100)"/><div class="question"><div class="meta">{{typeName[current.type]}} · {{current.difficulty==='easy'?'简单':'中等'}}</div><h3>{{index+1}}. {{current.content}}</h3><el-radio-group v-if="current.type==='single'||current.type==='judge'" v-model="answer" class="answers"><el-radio v-for="o in normalizedOptions" :key="o.optionKey" :value="o.optionKey" border>{{o.optionKey}}. {{o.content}}</el-radio></el-radio-group><el-checkbox-group v-else-if="current.type==='multiple'" v-model="multi" class="answers"><el-checkbox v-for="o in normalizedOptions" :key="o.optionKey" :value="o.optionKey" border>{{o.optionKey}}. {{o.content}}</el-checkbox></el-checkbox-group><el-input v-else v-model="answer" placeholder="请输入答案"/>
<el-alert v-if="judge" :type="judge.correct?'success':'error'" :title="judge.correct?'回答正确':'回答错误'" show-icon :closable="false"><p>标准答案：{{judge.standardAnswer}}</p><p>解析：{{judge.analysis}}</p></el-alert><el-button v-if="!judge" type="primary" :disabled="!answerValue" @click="submit">提交并即时评判</el-button><el-button v-else type="primary" @click="next">{{index===questions.length-1?'完成训练':'下一题'}}</el-button></div></template>
<template v-else><el-result icon="success" title="训练完成" :sub-title="`得分 ${result.score}，正确率 ${result.accuracy}%（${result.correctCount}/25）`"><template #extra><el-button type="primary" @click="reset">再练一次</el-button></template></el-result><h3 v-if="result.wrongAnswers?.length">错题解析</h3><el-collapse><el-collapse-item v-for="(w,i) in result.wrongAnswers" :key="i" :title="`${i+1}. ${w.content}`"><p>你的答案：{{w.answer||'未作答'}}</p><p>标准答案：{{w.standardAnswer}}</p><p>解析：{{w.analysis}}</p></el-collapse-item></el-collapse></template>
</div></template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {ElMessage} from 'element-plus';import {getTrainingCourses,startTraining,answerTraining,finishTraining} from '../../api/exercise.js';
const courses=ref([]),courseId=ref(''),stage=ref('select'),loading=ref(false),trainingId=ref(''),questions=ref([]),index=ref(0),answer=ref(''),multi=ref([]),judge=ref(null),result=ref({});const typeName={single:'单选题',multiple:'多选题',judge:'判断题',blank:'填空题'};const current=computed(()=>questions.value[index.value]||{});const normalizedOptions=computed(()=>current.value.type==='judge'&&!(current.value.options?.length)?[{optionKey:'true',content:'正确'},{optionKey:'false',content:'错误'}]:current.value.options||[]);const answerValue=computed(()=>current.value.type==='multiple'?[...multi.value].sort().join(''):answer.value.trim());onMounted(async()=>courses.value=await getTrainingCourses());async function start(){loading.value=true;try{const d=await startTraining(courseId.value);trainingId.value=d.trainingId;questions.value=d.questions;stage.value='answer'}finally{loading.value=false}}async function submit(){judge.value=await answerTraining(trainingId.value,{exerciseId:current.value.id,answer:answerValue.value})}async function next(){if(index.value===questions.value.length-1){result.value=await finishTraining(trainingId.value);stage.value='result';return}index.value++;answer.value='';multi.value=[];judge.value=null}function reset(){stage.value='select';courseId.value='';index.value=0;result.value={};ElMessage.success('可重新选择课程训练')}
</script><style scoped>.page{background:#fff;padding:28px;border-radius:16px;min-height:500px}.muted,.meta{color:#909399}.chooser{display:flex;gap:16px;margin-top:28px}.chooser .el-select{width:440px}.top{display:flex;justify-content:space-between}.question{max-width:820px;margin:32px auto;display:grid;gap:24px}.answers{display:grid;gap:12px}.answers .el-radio,.answers .el-checkbox{margin:0;width:100%}</style>
