import request from '../utils/request'
export const teacherRooms = () => request.get('/live/teacher/rooms')
export const studentRooms = () => request.get('/live/student/rooms')
export const createRoom = data => request.post('/live/rooms', data)
export const updateRoom = (id,data) => request.put(`/live/rooms/${id}`,data)
export const deleteRoom = id => request.delete(`/live/rooms/${id}`)
export const roomDetail = id => request.get(`/live/rooms/${id}`)
export const startRoom = id => request.post(`/live/rooms/${id}/start`)
export const endRoom = id => request.post(`/live/rooms/${id}/end`)
export const setReplay = (id,url) => request.put(`/live/rooms/${id}/replay`,{url})
export const credential = (id,role) => request.get(`/live/rooms/${id}/credential`,{params:{role}})
export const sendComment = (id,content) => request.post(`/live/rooms/${id}/comments`,{content})
export const likeRoom = id => request.post(`/live/rooms/${id}/likes`)
export const applyMic = id => request.post(`/live/rooms/${id}/mic-requests`)
export const handleMic = (id,requestId,approved) => request.put(`/live/rooms/${id}/mic-requests/${requestId}`,{approved})
export const teacherReplays = () => request.get('/live/teacher/replays')
export const studentReplays = () => request.get('/live/student/replays')
export const deleteReplay = id => request.delete(`/live/rooms/${id}/replay`)
